library(tidyverse)
library(data.table)
print("WHY")
print(506*51)
print("Which languages should I learn?")
print("Why did my configuration work?\Was it due to the elimination of 'global' as an option?")